// S7-R5 (PR-10, PR-2): qualified expm, cgs and bicgstab (D-029). Uses the helpers of tests/cases/s7_r1.hpp
// (namespace s7) and tests/cases/s7_r4.hpp (namespace s7r4). The scipy references were computed once with
// scipy.linalg.expm (scipy 1.18.1) and pasted as literals; they are not regenerated by the suite.
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <vector>

namespace s7r5
{
    using s7::mat;
    using s7::real_t;
    using cd = std::complex< double >;

    template< typename T >
    bool all_finite( mat< T > const& m )
    {
        for ( auto const& x : m )
            if ( !std::isfinite( std::real( x ) ) || !std::isfinite( std::imag( x ) ) ) return false;
        return true;
    }

    template< typename T >
    real_t< T > rel_err( mat< T > const& x, mat< T > const& ref )
    {
        mat< T > d{ x.row(), x.col() };
        for ( std::size_t i = 0; i != x.row(); ++i )
            for ( std::size_t j = 0; j != x.col(); ++j ) d[i][j] = x[i][j] - ref[i][j];
        return s7r4::frob( d ) / s7r4::frob( ref );
    }

    template< typename T >
    void check_expm_exact()
    {
        // zero → I exactly, also 0×0
        mat< T > const z{ 4, 4, T( 0 ) };
        CHECK( feng::expm( z ) == feng::eye< T >( 4, 4 ) );
        CHECK( feng::expm( mat< T >{} ).size() == 0 );
        // diagonal → diag(exp(a_ii)) exactly, diag(700) finite
        mat< T > d{ 3, 3, T( 0 ) };
        d[0][0] = T( 1.5 ); d[1][1] = T( -2.25 ); d[2][2] = T( 700 );
        mat< T > const e = feng::expm( d );
        for ( std::size_t i = 0; i != 3; ++i )
            for ( std::size_t j = 0; j != 3; ++j )
                CHECK( e[i][j] == ( i == j ? std::exp( d[i][i] ) : T( 0 ) ) );
        CHECK( all_finite( e ) );
        mat< T > d700{ 2, 2, T( 0 ) };
        d700[0][0] = d700[1][1] = T( 700 );
        mat< T > const e700 = feng::expm( d700 );
        CHECK( e700[0][0] == std::exp( T( 700 ) ) );
        CHECK( e700[0][1] == T( 0 ) );
    }

    template< typename T >
    void check_expm_extreme()
    {
        // ‖A‖₁ ≈ 1e10, negative definite Jordan block: exp(A) = e^{-1e10}·[[1, 1], [0, 1]] = 0 in double
        mat< T > const a = s7::from_real< T >( 2, 2, { -1e10, 1, 0, -1e10 } );
        mat< T > const ea = feng::expm( a );
        REQUIRE( all_finite( ea ) );
        for ( auto const& x : ea ) CHECK( std::abs( x ) <= 1e-300 );
        // nilpotent with ‖A‖₁ = 1e10: exp(A) = I + A
        mat< T > const n = s7::from_real< T >( 2, 2, { 0, 1e10, 0, 0 } );
        mat< T > const en = feng::expm( n );
        REQUIRE( all_finite( en ) );
        CHECK( en[0][0] == T( 1 ) );
        CHECK( en[1][1] == T( 1 ) );
        CHECK( en[1][0] == T( 0 ) );
        CHECK( std::abs( en[0][1] - T( 1e10 ) ) <= 1e10 * 64 * s7::eps< T >() );
        // ‖A‖₁ ≈ 1e300, negative definite (−1e300·I plus a small off-diagonal): exp(A) = 0 in double
        mat< T > b = s7::from_real< T >( 3, 3, { -1e300, 1, 0, 0, -1e300, 2, 1, 0, -1e300 } );
        mat< T > const eb = feng::expm( b );
        REQUIRE( all_finite( eb ) );
        for ( auto const& x : eb ) CHECK( std::abs( x ) <= 1e-300 );
    }

    template< typename T >
    void check_expm_nonfinite()
    {
        mat< T > a = s7::from_real< T >( 2, 3, { 1, 2, 3, 4, 5, 6 } ); // only the shape matters for the NaN result
        mat< T > sq = s7::from_real< T >( 2, 2, { 1, 2, 3, 4 } );
        sq[0][1] = T( std::numeric_limits< real_t< T > >::quiet_NaN() );
        mat< T > const e = feng::expm( sq );
        REQUIRE( e.row() == 2 );
        REQUIRE( e.col() == 2 );
        for ( auto const& x : e ) CHECK( std::isnan( std::real( x ) ) );
        sq[0][1] = T( std::numeric_limits< real_t< T > >::infinity() );
        for ( auto const& x : feng::expm( sq ) ) CHECK( std::isnan( std::real( x ) ) );

        mat< T > out = a;
        CHECK( feng::expm( sq, out ) == feng::linalg_status::nonfinite );
        CHECK( out == a );
        mat< T > const ok_in = s7::from_real< T >( 2, 2, { 0, 1, 0, 0 } );
        CHECK( feng::expm( ok_in, out ) == feng::linalg_status::ok );
        CHECK( out == s7::from_real< T >( 2, 2, { 1, 1, 0, 1 } ) );
    }

    // complex<double> closed forms: zero, a diagonal with complex entries, a nilpotent block, rotation generators
    inline void check_expm_complex_closed_form()
    {
        double const eps = std::numeric_limits< double >::epsilon();
        // zero → I exactly
        CHECK( feng::expm( mat< cd >{ 3, 3, cd( 0 ) } ) == feng::eye< cd >( 3, 3 ) );
        // diagonal with complex entries → diag(exp(a_ii)) exactly
        mat< cd > d{ 3, 3, cd( 0 ) };
        d[0][0] = cd( 0.5, 2.0 ); d[1][1] = cd( -1.25, -3.0 ); d[2][2] = cd( 0, 3.141592653589793 );
        mat< cd > const ed = feng::expm( d );
        for ( std::size_t i = 0; i != 3; ++i )
            for ( std::size_t j = 0; j != 3; ++j ) CHECK( ed[i][j] == ( i == j ? std::exp( d[i][i] ) : cd( 0 ) ) );
        // nilpotent with a complex entry: exp(A) = I + A
        mat< cd > nil{ 2, 2, cd( 0 ) };
        nil[0][1] = cd( 3, -4 );
        mat< cd > const en = feng::expm( nil );
        CHECK( en[0][0] == cd( 1 ) );
        CHECK( en[1][0] == cd( 0 ) );
        CHECK( en[1][1] == cd( 1 ) );
        CHECK( std::abs( en[0][1] - cd( 3, -4 ) ) <= 64 * eps * 5 );
        // rotation generator θ·[[0, −1], [1, 0]] → [[cos θ, −sin θ], [sin θ, cos θ]], and the unitary generator
        // iθ·[[0, 1], [1, 0]] → [[cos θ, i sin θ], [i sin θ, cos θ]]; θ = 7.5 takes one squaring
        for ( double const th : { 0.75, 7.5 } )
        {
            INFO( "theta " << th );
            double const c = std::cos( th ), sn = std::sin( th );
            mat< cd > const rot = s7r4::from_list< cd >( 2, 2, { 0, -th, th, 0 } );
            mat< cd > const want_rot = s7r4::from_list< cd >( 2, 2, { c, -sn, sn, c } );
            CHECK( rel_err( feng::expm( rot ), want_rot ) <= 64 * 2 * eps );
            mat< cd > const uni = s7r4::from_list< cd >( 2, 2, { 0, cd( 0, th ), cd( 0, th ), 0 } );
            mat< cd > const want_uni = s7r4::from_list< cd >( 2, 2, { c, cd( 0, sn ), cd( 0, sn ), c } );
            CHECK( rel_err( feng::expm( uni ), want_uni ) <= 64 * 2 * eps );
        }
    }
} // namespace s7r5

TEST_CASE( "S7-R5 expm of zero, diagonal and extreme inputs", "[S7][S7-R5]" )
{
    s7r5::check_expm_exact< double >();
    s7r5::check_expm_exact< std::complex< double > >();
    s7r5::check_expm_extreme< double >();
    s7r5::check_expm_extreme< std::complex< double > >();
    s7r5::check_expm_nonfinite< double >();
    s7r5::check_expm_nonfinite< std::complex< double > >();
    s7r5::check_expm_complex_closed_form();
}

TEST_CASE( "S7-R5 expm matches scipy references", "[S7][S7-R5]" )
{
    using s7r5::cd;
    // numpy default_rng(20261002).standard_normal((4, 4))·1.5, ‖A‖₁ = 5.94 (one squaring)
    feng::matrix< double > const a = s7::from_real< double >( 4, 4, {
        -0.3286716625089818, 1.3936606226964554, 0.9329334716081147, -0.5252792304594791,
        -1.4850480371190857, 1.1163261934688191, -1.2310979653076153, -1.3662397422059085,
        -4.039856710035755, 0.17777160587229968, -1.3625704897147035, -0.9038952069773634,
        0.08226996372122795, 1.4618974388691317, -0.6853026895932535, 1.0294510878328045 } );
    feng::matrix< double > const ea = s7::from_real< double >( 4, 4, {
        -0.24853487600479163, 0.02684645019835008, 0.1877005400720356, -1.4615747395214558,
        -0.027256558343341286, 0.615888790885136, -0.3779660471406582, -1.8867428635129848,
        -0.6608926016705973, -1.5528185729439463, 0.28883482828891993, 1.0857401605634964,
        0.502285296362307, 3.4658676324552617, -1.522872575272041, 0.8457065877396357 } );
    CHECK( s7r5::rel_err( feng::expm( a ), ea ) <= 1e-12 );
    CHECK( s7r5::rel_err( feng::expm( a.astype< cd >() ), ea.astype< cd >() ) <= 1e-12 );

    // ‖B‖₁ = 12 (two squarings)
    feng::matrix< double > const b = s7::from_real< double >( 4, 4, {
        2.0, -1.0, 4.0, 0.5, 3.0, -4.0, 1.5, 2.0, -2.0, 1.0, 0.0, 6.0, 5.0, -3.0, 2.0, -1.0 } );
    feng::matrix< double > const eb = s7::from_real< double >( 4, 4, {
        39.564648851459076, -16.323279303838085, 50.582129012167115, 51.159244877194794,
        25.995824630946895, -10.660783809409793, 33.15430503812922, 33.46526275298682,
        28.98727302293373, -12.169515854397675, 37.00243940975122, 37.582347827381284,
        31.417721978674933, -13.006598079333658, 40.14491115851765, 40.57335340586671 } );
    CHECK( s7r5::rel_err( feng::expm( b ), eb ) <= 1e-12 );

    // complex 3×3
    feng::matrix< cd > const c = s7r4::from_list< cd >( 3, 3, {
        { 0.5, 0.25 }, { -1.0, 0.5 }, { 0.25, 0 }, { 0, 0.75 }, { -0.5, 0 }, { 1.0, -0.25 }, { 1.5, 0 }, { 0.125, -0.5 }, { -0.25, 1 } } );
    feng::matrix< cd > const ec = s7r4::from_list< cd >( 3, 3, {
        { 1.3712706767213854, 0.15597657831225087 }, { -0.9684029456415137, 0.4506778282412952 }, { -0.24284452567538198, 0.3057490979511099 },
        { 0.6926061294227425, 0.8112756454504476 }, { 0.29043359311825423, -0.3757626571722854 }, { 0.5950516957178404, 0.1462719441204775 },
        { 1.5838751698156879, 0.789176073738423 }, { -0.5724612615097182, -0.16102754172923112 }, { 0.43237367668175875, 0.6762943510856989 } } );
    CHECK( s7r5::rel_err( feng::expm( c ), ec ) <= 1e-12 );
}

namespace s7r5
{
    inline double residual( mat< double > const& a, mat< double > const& x, mat< double > const& b )
    {
        double s = 0;
        for ( std::size_t i = 0; i != a.row(); ++i )
        {
            double r = -b[i][0];
            for ( std::size_t j = 0; j != a.col(); ++j ) r += a[i][j] * x[j][0];
            s += r * r;
        }
        return std::sqrt( s );
    }

    inline double norm2( mat< double > const& b ) { return s7r4::frob( b ); }

    template< typename Solver >
    void check_solver( Solver solve )
    {
        double const eps = 1e-10;
        // SPD 5×5: Bᵀ·B + 5·I
        mat< double > const g = s7::random_square< double >( 5, 2026 );
        mat< double > spd{ 5, 5 };
        for ( std::size_t i = 0; i != 5; ++i )
            for ( std::size_t j = 0; j != 5; ++j )
            {
                double s = i == j ? 5.0 : 0.0;
                for ( std::size_t k = 0; k != 5; ++k ) s += g[k][i] * g[k][j];
                spd[i][j] = s;
            }
        mat< double > const b = s7::from_real< double >( 5, 1, { 1, -2, 3, 0.5, -1 } );
        mat< double > x;
        CHECK( solve( spd, x, b, 100, eps ) == 0 );
        CHECK( residual( spd, x, b ) <= 10 * eps * norm2( b ) );

        // relative: a b of size 1e8 converges with the same eps
        mat< double > const big = b * 1e8;
        mat< double > xb;
        CHECK( solve( spd, xb, big, 100, eps ) == 0 );
        CHECK( residual( spd, xb, big ) <= 10 * eps * norm2( big ) );

        // diagonal
        mat< double > dg{ 5, 5, 0.0 };
        for ( std::size_t i = 0; i != 5; ++i ) dg[i][i] = double( i + 1 );
        mat< double > xd;
        CHECK( solve( dg, xd, b, 100, eps ) == 0 );
        CHECK( residual( dg, xd, b ) <= 10 * eps * norm2( b ) );

        // zero b: x = 0 and 0
        mat< double > x0 = s7::from_real< double >( 5, 1, { 1, 2, 3, 4, 5 } );
        CHECK( solve( spd, x0, mat< double >{ 5, 1, 0.0 }, 100, eps ) == 0 );
        CHECK( x0 == mat< double >{ 5, 1, 0.0 } );

        // NaN in b and in A: 1
        mat< double > bn = b;
        bn[2][0] = std::numeric_limits< double >::quiet_NaN();
        mat< double > xn;
        CHECK( solve( spd, xn, bn, 100, eps ) == 1 );
        mat< double > an = spd;
        an[1][3] = std::numeric_limits< double >::infinity();
        CHECK( solve( an, xn, b, 100, eps ) == 1 );
    }

    template< typename Solver >
    void check_solver_exhaustion( Solver solve )
    {
        // max_loops = 1 on an unconverged 5×5 system: 1, and x holds the (finite) last iterate
        mat< double > a{ 5, 5, 0.0 };
        for ( std::size_t i = 0; i != 5; ++i )
        {
            a[i][i] = 4.0;
            if ( i + 1 != 5 ) a[i][i + 1] = a[i + 1][i] = -1.0;
        }
        a[0][4] = 0.5; a[4][0] = 0.5;
        mat< double > const b = s7::from_real< double >( 5, 1, { 1, -2, 3, 0.5, -1 } );
        mat< double > x;
        CHECK( solve( a, x, b, 1, 1e-14 ) == 1 );
        REQUIRE( x.row() == 5 );
        REQUIRE( x.col() == 1 );
        CHECK( all_finite( x ) );
        CHECK( residual( a, x, b ) > 1e-14 * norm2( b ) );
        // more loops converge from the same start
        mat< double > y;
        CHECK( solve( a, y, b, 100, 1e-12 ) == 0 );
        CHECK( residual( a, y, b ) <= 10 * 1e-12 * norm2( b ) );
    }

    template< typename Solver >
    void check_solver_breakdown( Solver solve )
    {
        // breakdown: with A = [[0, 1], [1, 0]], b = (2, 0) and the start x₀ = (0, 1) the first residual is
        // r = (1, 0) and r̂ᵀ·A·r = 0, the denominator of α: 1, x the finite last iterate x₀, no NaN
        mat< double > const a = s7::from_real< double >( 2, 2, { 0, 1, 1, 0 } );
        mat< double > const b = s7::from_real< double >( 2, 1, { 2, 0 } );
        mat< double > const x0 = s7::from_real< double >( 2, 1, { 0, 1 } );
        mat< double > x = x0;
        CHECK( solve( a, x, b, 100, 1e-10 ) == 1 );
        REQUIRE( x.row() == 2 );
        REQUIRE( x.col() == 1 );
        CHECK( all_finite( x ) );
        CHECK( x == x0 );

        // nonfinite A or b: 1, x unchanged and finite
        mat< double > const spd = s7::from_real< double >( 3, 3, { 4, 1, 0, 1, 3, 1, 0, 1, 2 } );
        mat< double > const b3 = s7::from_real< double >( 3, 1, { 1, 2, 3 } );
        mat< double > const start = s7::from_real< double >( 3, 1, { 0.5, -1, 2 } );
        for ( int which = 0; which != 4; ++which )
        {
            INFO( "nonfinite case " << which );
            mat< double > an = spd, bn = b3;
            if ( which == 0 ) an[2][1] = std::numeric_limits< double >::quiet_NaN();
            if ( which == 1 ) an[0][0] = -std::numeric_limits< double >::infinity();
            if ( which == 2 ) bn[1][0] = std::numeric_limits< double >::infinity();
            if ( which == 3 ) bn[0][0] = std::numeric_limits< double >::quiet_NaN();
            mat< double > xs = start;
            CHECK( solve( an, xs, bn, 100, 1e-10 ) == 1 );
            CHECK( xs == start );
            CHECK( all_finite( xs ) );
        }

        // a diagonal system with mixed signs and scales converges to the relative tolerance
        mat< double > dg{ 5, 5, 0.0 };
        double const diag[5] = { -2, 3, 0.5, -7, 1e3 };
        for ( std::size_t i = 0; i != 5; ++i ) dg[i][i] = diag[i];
        mat< double > const bd = s7::from_real< double >( 5, 1, { 1, -2, 3, 0.5, -1 } );
        mat< double > xd;
        CHECK( solve( dg, xd, bd, 100, 1e-10 ) == 0 );
        CHECK( residual( dg, xd, bd ) <= 10 * 1e-10 * norm2( bd ) );
    }
} // namespace s7r5

TEST_CASE( "S7-R5 iterative solvers report exhaustion", "[S7][S7-R5]" )
{
    using M = feng::matrix< double >;
    auto cgs = []( M const& a, M& x, M const& b, std::uint_least64_t l, double e ) { return feng::cgs( a, x, b, l, e ); };
    auto cgs2 = []( M const& a, M& x, M const& b, std::uint_least64_t l, double e ) { return feng::conjugate_gradient_squared( a, x, b, l, e ); };
    auto bi = []( M const& a, M& x, M const& b, std::uint_least64_t l, double e ) { return feng::bicgstab( a, x, b, l, e ); };
    auto bi2 = []( M const& a, M& x, M const& b, std::uint_least64_t l, double e ) { return feng::biconjugate_gradient_stabilized_method( a, x, b, l, e ); };
    s7r5::check_solver_exhaustion( cgs );
    s7r5::check_solver_exhaustion( bi );
    s7r5::check_solver( cgs );
    s7r5::check_solver( cgs2 );
    s7r5::check_solver( bi );
    s7r5::check_solver( bi2 );
    s7r5::check_solver_breakdown( cgs );
    s7r5::check_solver_breakdown( cgs2 );
    s7r5::check_solver_breakdown( bi );
    s7r5::check_solver_breakdown( bi2 );
}
