#ifndef _TR_HPP_INCLUDED_SDFIO398YSFADKLJCSF98Y4KHSAFOIHVXKJNSDAKJHALKJHSFDJVCKJHSFAIUYHR4KHSFHUJS84
#define _TR_HPP_INCLUDED_SDFIO398YSFADKLJCSF98Y4KHSAFOIHVXKJNSDAKJHALKJHSFDJVCKJHSFAIUYHR4KHSFHUJS84

#include <matrix/matrix.hpp>

namespace feng
{
    template<typename Matrix>
    typename Matrix::value_type tr( const Matrix& m )
    {
        return m.tr();
    }

}//namespace feng

#endif//_TR_HPP_INCLUDED_SDFIO398YSFADKLJCSF98Y4KHSAFOIHVXKJNSDAKJHALKJHSFDJVCKJHSFAIUYHR4KHSFHUJS84

