#ifndef _TRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO
#define _TRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO

#include <matrix/matrix.hpp>

namespace feng
{

    template<typename Matrix>
    Matrix const transpose( const Matrix& m )
    {
        return m.transpose();
    }

}//namespace feng

#endif//_TRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO

