#ifndef MCTRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO
#define MCTRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO

#include "../numeric/math.hpp"


namespace f
{
    template<typename T, typename A>
    matrix<std::complex<T>, A> const ctranspose( const matrix<std::complex<T>, A>& m )
    {
        return conj( m.transpose() );
    }

}//namespace f

#endif//_CTRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO

