#ifndef MDET_HPP_INCLUDED_SDOFJIWEOUIJASFLDKJSAFLJKASFOIJSAFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDF
#define MDET_HPP_INCLUDED_SDOFJIWEOUIJASFLDKJSAFLJKASFOIJSAFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDF

namespace f
{

    template<typename T, typename A>
    T const det( const matrix<T, A>& m )
    {
        return m.det();
    }

}//namespace f

#endif//_DET_HPP_INCLUDED_SDOFJIWEOUIJASFLDKJSAFLJKASFOIJSAFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDF

