#ifndef MMAX_HPP_INCLUDED_SFDOJI4938YUALFKJALKHDSFIUHVCJSBANFDKIJUH4EU7HFDSKJHASIUH4E87UGHFASIDUHASFI
#define MMAX_HPP_INCLUDED_SFDOJI4938YUALFKJALKHDSFIUHVCJSBANFDKIJUH4EU7HFDSKJHASIUH4E87UGHFASIDUHASFI


namespace f
{
    template< typename T, typename A>
    T const
    max( const matrix<T, A>& m )
    {
        assert( m.size() );
        return *std::max_element( m.begin(), m.end() );
    }

}//namespace f

#endif//_MAX_HPP_INCLUDED_SFDOJI4938YUALFKJALKHDSFIUHVCJSBANFDKIJUH4EU7HFDSKJHASIUH4E87UGHFASIDUHASFI

