#ifndef MTR_HPP_INCLUDED_SDFIO398YSFADKLJCSF98Y4KHSAFOIHVXKJNSDAKJHALKJHSFDJVCKJHSFAIUYHR4KHSFHUJS84
#define MTR_HPP_INCLUDED_SDFIO398YSFADKLJCSF98Y4KHSAFOIHVXKJNSDAKJHALKJHSFDJVCKJHSFAIUYHR4KHSFHUJS84

namespace f
{
    template<typename Matrix>
    typename Matrix::value_type tr( const Matrix& m )
    {
        return m.tr();
    }

}//namespace f

#endif//_TR_HPP_INCLUDED_SDFIO398YSFADKLJCSF98Y4KHSAFOIHVXKJNSDAKJHALKJHSFDJVCKJHSFAIUYHR4KHSFHUJS84

