#ifndef MTRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO
#define MTRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO

namespace f
{

    template<typename Matrix>
    Matrix const transpose( const Matrix& m )
    {
        return m.transpose();
    }

}//namespace f

#endif//_TRANSPOSE_HPP_INCLUDED_SDIOJ4EIJFJIEIORJOFIWJVKLJJKSFDNVNNNNNNNNNNNNNNNNNNNNNNNNSFDKJHASJDO

